### PR TITLE
Bugfix read specific sysfs value "off" of session attribute

### PR DESCRIPTION
**Pull request by hawkxiang**
Linux kernel convert session_attr int value "off" to -1 in scsi_transport_iscsi  module. 
image

But open-iscsi don't convert special value "off" to -1. It will mistake session attibute info display.  
example: If set recovery_tmo "off"(`echo off > /sys/class/iscsi_session/session808/recovery_tmo`), this means  recovery_tmo=-1.  But (`iscsiadm -m session -P 3`) will mistake output "Recovery Timeout: 0".
image

### CODE REVIEW

**Comment by gonzoleeman** [comment]
Good catch, but what about the code in iscsi_sysfs.c/sysfs.c in usr, which read the same values. (Yes, the code is somewhat duplicated.)

It looks like this code might just work, by accident, since it tries to read an integer from recovery_tmo, and if it fails, it sets the value to -1, which is what we want when we read "off" anyway. :(

**Comment by hawkxiang** [comment]
@gonzoleeman  I think iscsi_sysfs.c/sysfs.c **can not** work well. Since `sysfs_get_int` always success(not fails), when read "off" as integer, and  sets the value to 0.
step1: `sysfs_get_value` read a string(example: "off") successful. Goto step2, not return EIO.
step2: `atoi` convert "off" to integer will return 0(not -1), so `*value = 0`. And `sysfs_get_int` return 0 (success).
image

I push a new commit to fix this bug.  Is only attribute of iscsi_session convert "off" to -1 ? since `sysfs_get_int` used  in many code segments.

**Comment by gonzoleeman** [comment]
I was just about to merge this, but I see you force-pushed a change. What was that for?

**Comment by hawkxiang** [comment]
> I was just about to merge this, but I see you force-pushed a change. What was that for?

I don't change bugfix commit code. You can merge this PR.
I drop a new commit which not related to this issue, after the PR.

**Comment by hawkxiang** [comment]
> I was just about to merge this, but I see you force-pushed a change. What was that for?
@gonzoleeman 
I don't change bugfix commit code. You can merge this PR.
I drop a new commit which not related to this issue, in this branch which after the PR.

**Comment by gonzoleeman** [comment]
> > I was just about to merge this, but I see you force-pushed a change. What was that for?
> 
> @gonzoleeman I don't change anything. You can merge this. I push a new commit(**[c747fde](https://github.com/open-iscsi/open-iscsi/commit/c747fde989e4ab91412dfc7a87211cf5a3c01c55)**) after the PR which not related to this issue. So I drop the new commit(**[c747fde](https://github.com/open-iscsi/open-iscsi/commit/c747fde989e4ab91412dfc7a87211cf5a3c01c55)**) and force-pushed rollback branch to PR initial state(only **[bf5fdba](https://github.com/open-iscsi/open-iscsi/commit/bf5fdbafb2b54deb796448c93538d53c80a5fdac)** commit).

The problem is that when you push a new commit to this branch, github updates the pull request to include the new commit.

Can you back up your branch one commit (to avoid the new commit) and force-push it?

**Comment by hawkxiang** [comment]
> > > I was just about to merge this, but I see you force-pushed a change. What was that for?
> > 
> > 
> > @gonzoleeman I don't change anything. You can merge this. I push a new commit(**[c747fde](https://github.com/open-iscsi/open-iscsi/commit/c747fde989e4ab91412dfc7a87211cf5a3c01c55)**) after the PR which not related to this issue. So I drop the new commit(**[c747fde](https://github.com/open-iscsi/open-iscsi/commit/c747fde989e4ab91412dfc7a87211cf5a3c01c55)**) and force-pushed rollback branch to PR initial state(only **[bf5fdba](https://github.com/open-iscsi/open-iscsi/commit/bf5fdbafb2b54deb796448c93538d53c80a5fdac)** commit).
> 
> The problem is that when you push a new commit to this branch, github updates the pull request to include the new commit.
> 
> Can you back up your branch one commit (to avoid the new commit) and force-push it?

I have done back up branch **one commit** and force-push it.  You can merge it.
image

If the pull request always has problem, I create a new pull request for this change: https://github.com/open-iscsi/open-iscsi/pull/468

**Comment by gonzoleeman** [comment]
Did you decide not to change the code that is not in libopeniscsiusr, i.e. usr/iscsi_sysfs.c?

I'm confused. This seemed simple, but it hasn't been.

**Comment by hawkxiang** [comment]
> Did you decide not to change the code that is not in libopeniscsiusr, i.e. usr/iscsi_sysfs.c?
> 
> I'm confused. This seemed simple, but it hasn't been.


OK, I have changed the code in `usr/sysfs.c` instead of `usr/iscsi_sysfs.c`. Because linux kernel code convert all iscsi_session attribute "off" to integer -1.
截屏2024-09-16 11 17 22

I have passed the new code test. 
Env: 1. setting recovery_tmo "off"(`echo off > /sys/class/iscsi_session/session808/recovery_tmo`). 2. add debug log in function `iscsi_sysfs_get_sessioninfo_by_id` of usr/iscsi_sysfs.c, like this.
截屏2024-09-16 11 26 12

Test: restart iscsid to test code, expect log output **"recovery_tmo -1"**.
1. **Before** code change：output "recovery_tmo 0", is a mistake.
截屏2024-09-16 11 00 19
2. **After** code change：output "recovery_tmo -1", is OK.
截屏2024-09-16 11 02 11

**Comment by gonzoleeman** [comment]
Thank you!

**Pull request merged**
