### PR TITLE
musl build fixes

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by gonzoleeman** [comment]
I will compile test these, but they all look reasonable at first glance.

**Comment by kraj** [comment]
@gonzoleeman any updates ?

**Comment by gonzoleeman** [comment]
Please make just the one change I requested, and I'll be glad to merge these into master

**Comment by kraj** [comment]
@gonzoleeman the reason is there in the commit message

```
including nic.h before linux/ethtool.h avoids redefinitions of
eth structs
```

**Comment by gonzoleeman** [comment]
People editing the code don't normally look at the git commit comments that added the code. Since the local includes traditionally go below the global includes, I can see somebody (like me) moving the include back down below, especially since it wouldn't break any non-musl compilers. So please add a simple comment, something like your commit comment? Is that asking too much?

**Comment by kraj** [comment]
Oh thats not a problem. It was not clear to me from earlier comment if you wanted the comment in the code itself. Let me do that and refresh the PR

**Comment by kraj** [comment]
@gonzoleeman done, please review and let me know if it needs some more work

**Pull request merged**
