### PR TITLE
Fix dprint call and ensure target discovery before login

### PR DESCRIPTION
**Pull request by jkchen1095**
Fix dprint import path and ensure target discovery to prevent login failure

### CODE REVIEW

**Comment by gonzoleeman** [comment]
Did you run the tests and observe a failure before your changes? If so, I'd like to know. I need to run the tests myself, partly to verify your changes, and partly to remind myself what the heck I did years ago. But if you have a failure you're fixing and know the message you got, that would help me.

**Comment by gonzoleeman** [comment]
I'd love to merge this if it actually fixes something ... no response?

**Comment by jkchen1095** [comment]
Hi, thanks for your response
I'm sorry I couldn't respond in time as I was on leave the past few days..
This project is great for testing my iSCSI environment.
Please see the test script and the failure log below.



1. Initiator test script `test.sh` (you may need to modify the IP, PORT, MAPPED_LUN_ID, TARGET_IQN, and DEVICE as per your setup):
```
#!/bin/bash

set -e

IP="127.0.0.1"
PORT="3260"
MAPPED_LUN_ID="5"
TARGET_IQN="iqn.2003-01.org.linux-iscsi.ubuntu22040005.x8664:sn.f639550892b8"
DEVICE="/dev/sda"

./test/test-open-iscsi.py -d -s 1 -v -c -f --target ${TARGET_IQN} --ipnr ${IP} --device ${DEVICE} TestRegression.test_HdrDigest_on_DataDigest_on
```

2. Failed without `util.dprint`

```
root@Ubuntu22040005:~/src/open-iscsi# sh ./test.sh
*** Starting TestRegression
...
======================================================================
ERROR: tearDownClass (harness.tests.TestRegression)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/src/open-iscsi/test/harness/tests.py", line 211, in tearDownClass
    print_time_values()
  File "/root/src/open-iscsi/test/harness/tests.py", line 34, in print_time_values
    r = s2dt(v)
  File "/root/src/open-iscsi/test/harness/tests.py", line 23, in s2dt
    dprint("s2dt: %f -> %s" % (s_orig, a_str))
NameError: name 'dprint' is not defined

======================================================================
...

----------------------------------------------------------------------
Ran 1 test in 3.366s

FAILED (failures=1, errors=1)

```

3. After fixing the dprint failure, we can see that test still failed without a preflight check for iscsi discovery
```

root@Ubuntu22040005:~/src/open-iscsi# sh test.sh
DEBUG: found: verbosity=2, target=iqn.2003-01.org.linux-iscsi.ubuntu22040005.x8664:sn.f639550892b8, ipnr=127.0.0.1, device=/dev/sda, bs=None
DEBUG: Found request for single: 0-1
DEBUG: subtest_list before:[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
DEBUG: subtest_list after:[1]
*** Starting TestRegression

.......
Logging in to [iface: default, target: iqn.2003-01.org.linux-iscsi.ubuntu22040005.x8664:sn.f639550892b8, portal: 127.0.0.1,3260]
......
======================================================================
FAIL: test_HdrDigest_on_DataDigest_on (harness.tests.TestRegression) [Testing FirstBurst=4096 MaxBurst=4096 MaxRecv=4096] (i=1)
Test With Header Digest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/src/open-iscsi/test/harness/tests.py", line 173, in test_HdrDigest_on_DataDigest_on
    self.run_the_rest()
  File "/root/src/open-iscsi/test/harness/tests.py", line 186, in run_the_rest
    self.assertEqual(res, 0, 'cannot login to device')
AssertionError: 8 != 0 : cannot login to device

----------------------------------------------------------------------
......
...
```

This is because the iscsiadm login requires the target to be present in the initiator's discovery cache (at least in my environment)

**Comment by jkchen1095** [comment]
Hi, could you please provide an update on the progress of this Merge Request review?

**Comment by gonzoleeman** [comment]
You are proposing two chages:

1. change drpint() to util.dprint(), and
2. do discovery each and every time time you run a test

For dprint, I am running the tests now from the "tests" subdirectory, and there is no problem with dprint(). I will try it next from the parent directory. If your proposal doesn't break anything, and it fixes an issue, I'll be glad to merge it.

For the second issue, I'm dubious. I can see that the README file does not explain that the target you are specifying needs to be in the discovery DB. So adding more info to the README file might address that. But I'm also open to having the test suite ensure that the node is in the DB, and either fail or run discovery *once*. There is no reason to run discovery each and every time a test is run, since once is enough. On the other hand, the tests are supposed to stand alone. Still, even if it was going to be done every test, I'd prefer a check of the node DB first, before running the test. And, for me, if the tests are going to run discovery every time, then then should (1) ensure the node DB is empty first (of at least that node), and (2) remove the node they created when the test is done.

So, for simplicity, I kind of like either (1) adding info to the README and leaving it manual, or (2) only doing discovery once, and just leaving it discovered when done (i.e. do not worry about cleanup -- info could be added to the README that a node is left in the DB).

Thoughts?

**Comment by gonzoleeman** [comment]
And I see that your test script effectively removes the node entry in the DB, before start, now, which is perhaps why your test is failing?

**Comment by gonzoleeman** [comment]
I have created a pull request. See #491 

This fixes your dprint() issue, and it adds in doing discovery if needed. That means that, for each test, it checks that the Node is in the DB, and runs discovery if it is not.

Please pull my branch and try it out. If my branch works, I will merge and and we can delete this pull request.

Note: the pull request also removes some old testing code, and it cleans up the testing code a tiny bit more.

**Comment by jkchen1095** [comment]
Hi [gonzoleeman](https://github.com/gonzoleeman)

Thanks for your contribution! I've tested your branch, and everything works perfectly on my end. The dprint() issue is resolved, and the discovery mechanism integrates smoothly.

Feel free to merge your branch and close this pull request whenever you're ready. Let me know if there's anything else you'd like me to check.

**Comment by gonzoleeman** [comment]
Closing this request, as I just merged the agreed-upon fixes. Thank you for finding these issues.

**Pull request closed without merging**
