### PR TITLE
Fix installation of libopeniscsiusr symlinks

### PR DESCRIPTION
**Pull request by phmccarty**
The install(1) command dereferences symlinks when copying to the target location, so use an alternate approach to create symlinks from scratch instead.

### CODE REVIEW

**Comment by gonzoleeman** [comment]
I'm not sure I understand the issue here. I'll have to look this over more.

**Comment by cleech** [comment]
Anyone want to autotool this up instead?  Or is it just me?

**Comment by gonzoleeman** [comment]
On Jun 13, 2018, at 12:13 PM, Chris Leech <notifications@github.com> wrote:
> 
> Anyone want to autotool this up instead? Or is it just me?
> 
> —
> 

I have no idea what autotool is, but if it automates creating the library links I’m all for it.
— 
Lee

**Comment by cleech** [comment]
> I have no idea what autotool is, but if it automates creating the library links I’m all for it.

Just the collective name for the automake / autoconf / libtool suite.  Has it's problems, but all build systems do, and I don't like trying to figure out these little details to maintain custom makefiles.

**Comment by cleech** [comment]
Merging this to fix creating libopeniscsiusr.so and libopeniscsiusr.so.0 as symlinks to the fully versioned file instead of making new copies.

Thanks.

**Pull request merged**
